### PR TITLE
Importing original version of topological navigation

### PR DESCRIPTION
**Pull request by Jailander**
from https://github.com/strands-project/strands_navigation

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I'll set this up on Jenkins for PR builds. Wait for that to pass before merging

**Comment by Jailander** [comment]
Nice, I'll make the PR removing these from strands Navigation later tonight

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
I have enabled, both `kinetic` and `melodic` tests :-)

**Comment by Jailander** [comment]
Thank you!! you are the greatest hero!!

**Pull request merged**
