### PR TITLE
Minor quality of life improvements for map_manager

### PR DESCRIPTION
**Pull request by heuristicus**
Additions:

- yaw and xy goal tolerances are no longer hardcoded in `add_topological_node` and so the defaults can be modified more easily
- vertices for the influence zone are generated by a function rather than hardcoded
- distance for determining close nodes is an optional parameter to `add_topological_node`

### CODE REVIEW

**Comment by bfalacerda** [comment]
Hi, could someone look at this please? @Jailander

**Comment by Jailander** [comment]
Hi, sorry I had missed this!!! looks good will test today

**Comment by bfalacerda** [comment]
Thanks! :)

**Comment by Jailander** [comment]
Love it! thanks @heuristicus will merge

**Pull request merged**
