### PR TITLE
Some Python3 and multi-robot fixes

### PR DESCRIPTION
**Pull request by marc-hanheide**
Apologies conflating two bugfixes into on PR, but it's simple (and late say @gcielniak):

1. the map converter didn't work in noetic
2. some topic names where "root-ed" that shouldn't be in multi-robot (namespace) setups

### CODE REVIEW

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
@Jailander can you briefly check, as I'm unsure if the `/`  in those topic names was there for a reason?

**Comment by Jailander** [comment]
@adambinch can you help me with this I have my hands full this week

**Review by adambinch — APPROVED** [review]
Tested the goal converter and a single robot sim. Both work fine.

**Comment by marc-hanheide** [comment]
Many thanks, I'll merge

**Pull request merged**
