### PR TITLE
Topological Navigation version 2 Master Branch

### PR DESCRIPTION
**Pull request by Jailander**
to be merged into master when we are ready to deploy new topo nav

### CODE REVIEW

**Comment by adambinch** [comment]
A new version of topological navigation (topological navigation 2 - https://github.com/LCAS/topological_navigation/tree/toponav2-devel) has been developed.  Myself and @Jailander  think that it is now at a stage where it can be merged into the master branch, with the current master branch moved to a `legacy` branch. Toponav 2 should be fully backwards compatible, such that everything in RASberry master  and SagaApps master should work with it. Before we proceed with the merging, it would be great if those of you who use toponav make sure that toponav 2 works for you.

I have put several people down for review whi I know/think uses toponav. If I have missed anyone and you want to test it please do so.

**Review by adambinch — APPROVED** [review]
Tested on several different tmaps. Everything working for me.

**Review by marc-hanheide — COMMENTED** [review]
I have not tested this in detail, but generally looks alright. However, please ensure you create a new "legacy" or "v1" branch from the "master" before this is merged. I'm also thinking if we want to rename the packages? I know there is a lot of legacy software (see https://raw.githubusercontent.com/wiki/LCAS/rosdistro/repos-melodic.svg) that we may not want to all update. Wouldn't it be wiser to, e.g., include a prefix like `tn2_` to the packages? Or are you confident they are fully interface-compatible? Then of course this is not required. This is to feed into a discussion mostly.

**Comment by marc-hanheide** [comment]
> I have not tested this in detail, but generally looks alright. However, please ensure you create a new "legacy" or "v1" branch from the "master" before this is merged. I'm also thinking if we want to rename the packages? I know there is a lot of legacy software (see https://raw.githubusercontent.com/wiki/LCAS/rosdistro/repos-melodic.svg) that we may not want to all update. Wouldn't it be wiser to, e.g., include a prefix like `tn2_` to the packages? Or are you confident they are fully interface-compatible? Then of course this is not required. This is to feed into a discussion mostly.

I have seen #83 but I wonder if and how many people maintaining legacy systems will be prepared to check in depth. A renaming would avoid the problem?

**Comment by adambinch** [comment]
> > I have not tested this in detail, but generally looks alright. However, please ensure you create a new "legacy" or "v1" branch from the "master" before this is merged. I'm also thinking if we want to rename the packages? I know there is a lot of legacy software (see https://raw.githubusercontent.com/wiki/LCAS/rosdistro/repos-melodic.svg) that we may not want to all update. Wouldn't it be wiser to, e.g., include a prefix like `tn2_` to the packages? Or are you confident they are fully interface-compatible? Then of course this is not required. This is to feed into a discussion mostly.
> 
> I have seen #83 but I wonder if and how many people maintaining legacy systems will be prepared to check in depth. A renaming would avoid the problem?

I am confident that they are fully interface compatible, but would like others to confirm this if possible. However, renaming the packages wouldn't be too much trouble. Would like to hear from @Jailander on this ...

**Comment by Jailander** [comment]
A legacy branch has been created from the current version of master see:
https://github.com/LCAS/topological_navigation/tree/legacy

**Review by nikostsagk — APPROVED** [review]

**Review by MikHut — APPROVED** [review]
This worked very with UV treatment and solved some problems we were having before, although could still do with further testing in the field.

**Pull request merged**
