### PR TITLE
Can now use the TEB local planner with topological navigation.

### PR DESCRIPTION
**Pull request by adambinch**

### CODE REVIEW

**Comment by Jailander** [comment]
test again please

**Comment by Jailander** [comment]
retest this please

**Comment by gpdas** [comment]
can this be closed?

**Comment by Jailander** [comment]
It should be merged

**Comment by gpdas** [comment]
is this different from #9 ?

**Comment by Jailander** [comment]
Oh I actually mistook it with #9 I'll close

**Pull request closed without merging**
