### PR TITLE
adding route cache

### PR DESCRIPTION
**Pull request by Jailander**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
4 hours can be a bit short… can we give a higher default (or make it configurable)? For @ZuyuanZhu work, he probably would want it for much longer to run many different experiments easily. 
one worry, of course is that the cache should include the map in its hash, as otherwise we’ll get awful side effects once called with a different map, right?

**Comment by Jailander** [comment]
yes, that was my train of thought when doing it rather short, I did think about deleting the cache when creating the object but then Iwasn't sure if that would have any side effect on @ZuyuanZhu framework

**Comment by Jailander** [comment]
I will try to have a play with making hashes with the map name so this is not a problem, however you might still have problems if you modify the map

**Comment by marc-hanheide** [comment]
due to these side effects, I think this really needs to be explicitly enabled and not on by default.

**Comment by Jailander** [comment]
Yeah, good call I will add that ASAP

**Comment by ZuyuanZhu** [comment]
Just tested the cachier. Unfortunately, the result is not good. With 1 polytunnel, we can get the result within 2.7s without cachier, but after adding cachier, almost 1 hour passed and I still haven't got the result.

The cachier is definitely working as I found the cache file size `.topological_navigation.route_search.search_route` keeps changing and the des simulation logs information very very slow. 

I'll stop the simulation now and try the cachier on the full CHF map to see whether we can get the time back.

**Pull request closed without merging**
