### PR TITLE
Update LCAS branch with SAGA branch

### PR DESCRIPTION
**Pull request by adambinch**
@marc-hanheide these are general improvements but you may not want this one https://github.com/LCAS/topological_navigation/pull/138/commits/8ce9ee5926b45a3ae2a1b11db9917b6404d40577 ?

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Thanks for this. The problem here is that the defined unit tests, e.g., https://github.com/SAGARobotics/topological_navigation/blob/038b42ba04d6c6964f7a66c6a57433235f82ed4e/topological_navigation/tests/travel_time_estimator.test and https://github.com/SAGARobotics/topological_navigation/blob/038b42ba04d6c6964f7a66c6a57433235f82ed4e/topological_navigation/tests/navigation_scenarios.test are still defined to start the `message_store` which obviously is no longer installed. These also should be amended, also for SAGA's own CI, @adambinch @baardkrk , right?

**Comment by adambinch** [comment]
@Jailander can we make versions of these tests that do not rely on mongodb?

**Comment by Jailander** [comment]
Eek that might be complex let me take a look tomorrow.
But it's more likely that we should have new tests.

**Comment by adambinch** [comment]
Ok to merge @marc-hanheide ?

**Comment by marc-hanheide** [comment]
it's more that you don't want that workflow,.right? cause it would try to push to your repo. so, I'd say revert the release commit in this PR

**Comment by adambinch** [comment]
@baardkrk can you remove those commits from this PR?

**Comment by baardkrk** [comment]
I'll remove the commits, however, won't they have to be removed every time we want to sync the saga commits to LCAS? Will this be done often in the future?

**Comment by adambinch** [comment]
> I'll remove the commits, however, won't they have to be removed every time we want to sync the saga commits to LCAS? Will this be done often in the future?

**Comment by adambinch** [comment]
> > I'll remove the commits, however, won't they have to be removed every time we want to sync the saga commits to LCAS? Will this be done often in the future?

Hope not :(

**Comment by adambinch** [comment]
Closing this as it is replaced by https://github.com/LCAS/topological_navigation/pull/139

**Pull request closed without merging**
